### PR TITLE
Parser error messages

### PR DESCRIPTION
**Pull request by salmans**

### CODE REVIEW

**Comment by KiChjang** [comment]
When it comes to handling error, I suggest using failure. It has a book which explains the different use cases for it: https://rust-lang-nursery.github.io/failure/

**Comment by salmans** [comment]
@KiChjang thanks, this is pretty neat! I'll update the code using failure.

**Comment by salmans** [comment]
@KiChjang with the exception of encouraging me to create custom error types, I guess I still don't have a good understanding about the problems that `failure` is solving. I can see how being able to cast all errors to a single type is useful but is there anything else that I'm missing?

**Comment by KiChjang** [comment]
Sorry for the unresponsiveness, I was in Beijing and now I'm in HK.

**Comment by salmans** [comment]
Dude no worries at all. I appreciate your help and your feedback has been very helpful.
Have fun in HK!

**Pull request merged**
