### PR TITLE
adding bounded and example theories

### PR DESCRIPTION
**Pull request by salmans**

### CODE REVIEW

**Comment by KiChjang** [comment]
@salmans I may setup rustfmt on this repo in the future so that you don't need to worry about formatting anymore.

**Comment by salman-xage** [comment]
@KiChjang I use intellij-rust for formatting. I need to learn more about rustfmt!

**Comment by salmans** [comment]
@KiChjang doesn't IntelliJ do that for me already?

**Comment by KiChjang** [comment]
It should if you've set it up; the formatting changes in this PR suggests to me that it hasn't been setup.

**Pull request merged**
